@url_dev=http://localhost:3056/v1/api/

### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 7858277b5e49f99122322eb2f7faeb3a602bdcb0d4f64a1a5b09cd36d169feb8f154cb38741cfb8f12a781012fd65a9cb547481180adbd85abf67a7b971edfaa

{
    "name": "Shop TIPS",
    "email": "shoptipjs08@gmail.com",
    "password": "abc123"
}