@url_dev=http://localhost:3056/v1/api/

### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 26e15c82f6518431fef6cd15b40dba30c03550c99181c1a6760a62007eb9a43ccab2b7f27c02def3ae7fa62f4ec0d34ce7cd43551f5fdbbb605a943a93bfea1c

{
    "name": "Shop TIPS",
    "email": "shopDevTipjs26@gmail.com",
    "password": "abc123"
}